### ISSUE TITLE
How does rediscover work ?

### ISSUE THREAD

**Issue by danielo515** [wzrdtales/seneca-mesh-ng#1]
Hello,

I'm glad you made this fork to add a very needed feature as rediscover is. However I'm not sure how it is supposed to work. Could you describe the scenarios it is able to solve and which ones not ?
I'm currently using it and all that I can see is that once all bases get down, services get isolated, and after starting the bases again services are not able to re-discover them.

Thanks in advance

**Comment by wzrdtales** [comment]
it worked for most of the time, but not all of the time. We lately published a way better covered version, only important thing is not to use any tags like some docs suggest, as this will segment the members, which is not really supported right now

**Comment by wzrdtales** [comment]
and before you wonder why I even answer, I know 4 years is a long time for an answer. we open sourced this module simply to share it with others, in the end we wrote it for us and it served good enough, but lately found enough time to look into the matter deeper why certain things still didn't work. Just wanting to let you know if it might still be helpful

**Comment by danielo515** [comment]
> and before you wonder why I even answer, I know 4 years is a long time for an answer. we open sourced this module simply to share it with others, in the end we wrote it for us and it served good enough, but lately found enough time to look into the matter deeper why certain things still didn't work. Just wanting to let you know if it might still be helpful

A late answer is better than nothing. Even if it is not useful for me anymore, it may help others
